### PR TITLE
eliminate a faraday 1.x deprecation warning

### PR DESCRIPTION
**Pull request by skaes**
See https://lostisland.github.io/faraday/middleware/authentication.

### CODE REVIEW

**Review by tnir — CHANGES_REQUESTED** [review]
It looks like changing here work well to me.

**Comment by skaes** [comment]
@tnir what change to the code do suggest? I can't find any.

**Comment by tnir** [comment]
I thought I would do that after I become a maintainer and release the gem.

**Comment by skaes** [comment]
I'll ry to fix the Ruby 2.2.10 problem.

**Comment by skaes** [comment]
@tnir sorry for the confusion. Should be complete by now.

**Review by tnir — APPROVED** [review]
Now it looks like everything works well 🎉 Thanks @skaes  🙏

**Pull request merged**
