### PR TITLE
Fixed: several test suite errors appearing on the fresh master checkout.

### LINKED ISSUE #184: Unit test failure on master
Running ```bundle install``` and then ```rake test``` generates the following error on the latest master:
```
  1) Error:
Geminabox::RubyGemDependencyTest#test_get_list:
ArgumentError: Unknown key: "content_type". Valid keys are: "headers", "status", "body", "exception", "should_timeout"
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/util/hash_validator.rb:12:in `block in validate_keys'
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/util/hash_validator.rb:10:in `each_key'
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/util/hash_validator.rb:10:in `validate_keys'
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/response.rb:80:in `options='
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/response.rb:25:in `initialize'
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/response.rb:15:in `new'
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/response.rb:15:in `response_for'
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/request_stub.rb:21:in `block in to_return'
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/request_stub.rb:21:in `map'
    /home/bkon/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/webmock-1.20.4/lib/webmock/request_stub.rb:21:in `to_return'
    /home/bkon/projects/geminabox/test/units/geminabox/rubygems_dependency_test.rb:14:in `test_get_list'
```

Seems to be caused by the parameter validation code recently added to webmock: https://github.com/bblimke/webmock/commit/505e9750c839d004b2b31e4b6a5bd1500e556ab6#diff-86e5a2a991ebd581c09757add511b879

Pull request is on the way.

### PR DESCRIPTION
**Pull request by bkon**
Fixes #184 and #185

### CODE REVIEW

**Comment by natebird** [comment]
:+1:

**Comment by reggieb** [comment]
I don't think this is a good test pattern:

```ruby
assert %w[
       my_gem-6.0
       my_gem-5.0
       my_gem-4.0
       my_gem-3.0
       my_gem-2.0
       unrelated_gem-1.0
-    ]
+    ].all? { |gem| gems_on_page.include? gem }
```

Because if one of the items is causing the problem, the test output will not tell you which one. For that reason, I'd suggest:

```ruby
%w[
     my_gem-6.0
     my_gem-5.0
     my_gem-4.0
     my_gem-3.0
     my_gem-2.0
     unrelated_gem-1.0]
 ].each do  |gem| 
  assert gems_on_page.include?(gem), "gems_on_page should include #{gem}"
end
```

**Comment by reggieb** [comment]
Or better still:

```ruby
expected = %w[
     my_gem-6.0
     my_gem-5.0
     my_gem-4.0
     my_gem-3.0
     my_gem-2.0
     unrelated_gem-1.0]
 ]
expected_in_gems_on_page = expected & gems_on_page
assert_equal expected, expected_in_gems_on_page
```
That will both allow for additional elements in gems_on_page, and output a meaningful comparison of expected and actual on failure.

**Comment by jrochkind** [comment]
I was considering to try and prepare a PR fixing current build failures, but I see this PR already exists un-merged. What's up?

**Comment by bkon** [comment]
@jrochkind I've actually missed @reggieb response... 

Alas, I'm no more using geminabox since Feb. It'd be awesome if anyone (@jrochkind, I'm looking at you) could take over the pull request and rewrite test assertion taking @reggieb suggestion into account.

**Pull request closed without merging**
