### PR TITLE
Fixes username/password extraction with Unescapes

### LINKED ISSUE #235: gem inabox command: username with an @ causes issues
I fixed it like this...

geminabox-0.13.0/lib/geminabox_client.rb

`@username, @password = URI.unescape(uri.user), URI.unescape(uri.password)
`
curl seems to be doing similar, so it should not cause too many surprises.

### PR DESCRIPTION
**Pull request by martinseener**
Fixes #235

### CODE REVIEW

**Comment by sonots** [comment]
URI.unescape is an obsolete method. Please use others

**Comment by martinseener** [comment]
@sonots it doesn't look obsolete nor deprecated, at least in the latest Ruby 2.4.0 Doc: http://ruby-doc.org/stdlib-2.4.0/libdoc/uri/rdoc/URI/Escape.html#method-i-unescape

**Comment by sonots** [comment]
Document is unclear, but it is actually obsolete https://github.com/ruby/ruby/blob/trunk/lib/uri/common.rb#L129

**Comment by martinseener** [comment]
Can you tell me what we should use instead to just fix this?!

**Comment by sonots** [comment]
URi escape tells as

> This method is obsolete and should not be used. Instead, use CGI.escape, URI.www_form_encode or URI.www_form_encode_component depending on your specific use case.

We should use opposite versions of them depending on our use case. I am unclear for the root cause of this issue. Could you investigate what is suitable for this case?

**Comment by martinseener** [comment]
Sorry, iam not that good in ruby, so maybe someone with more insight might help me out here!?

**Comment by sonots** [comment]
No progress on this. Let me close. Issues are still remained, though.

**Pull request closed without merging**
