### PR TITLE
remove File.exists? deprecation warning

### PR DESCRIPTION
**Pull request by skaes**
The replacement File.exist? has been around since at least 2006.

### CODE REVIEW

**Review by tnir — APPROVED** [review]

**Comment by tnir** [comment]
I think a maintainer should allow a new contributor to trigger Actions...

**Review by tnir — CHANGES_REQUESTED** [review]
Could you update the branch to include #383 as [some CI](https://github.com/geminabox/geminabox/runs/6909524332?check_suite_focus=true) is failing? 🙏

**Comment by skaes** [comment]
@tnir I can do this to move ahead quickly, but given that this fails only on ancient Ruby versions which are no longer supported by the Ruby maintainers and probably full of security issues, I'd like to ask why we would want to run tests for these versions at all? Or support them, for this matter.

BTW, adding restriction to the Gemfile does not help any users: when they install geminabox, they will get the wrong version of the multipart-post gem when the install it.

My suggestion is to move all gem dependencies in Gemfile to the gem spec.

**Review by tnir — APPROVED** [review]
🎉

**Pull request merged**
