### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
Signed-off-by: Mohit Saxena <76725454+mohitsaxenaknoldus@users.noreply.github.com>
#473

### CODE REVIEW

**Review by tnir — CHANGES_REQUESTED** [review]
If you want to remove `mkdir -p`, you should remove only a single line.

**Comment by mohitsaxenaknoldus** [comment]
> If you want to remove `mkdir -p`, you should remove only a single line.

Done

**Comment by mohitsaxenaknoldus** [comment]
@tnir Is this good to merge now?

**Comment by mohitsaxenaknoldus** [comment]
@tnir Does this need further changes?

**Pull request closed without merging**
