### PR TITLE
Feature/docker file

### PR DESCRIPTION
**Pull request by allcentury**
This commit adds a Dockerfile so users can easily spin up a container.  It should satisfy issue #199 .

### CODE REVIEW

**Comment by mehulkar** [comment]
:+1: for Dockerfile, but looks like this PR contains other changes as well?

**Comment by allcentury** [comment]
Thanks @mehulkar  -- I reverted back those test files.

**Comment by Primer42** [comment]
This would be very nice - how soon can we expect it to be merged?

**Comment by cwninja** [comment]
Loving the dockerisation.

@allcentury can you rebase and merge? I've granted you commit access.

**Comment by allcentury** [comment]
Done though I don't see the ability to merge.

**Pull request merged**
