### PR TITLE
Add Contributor Covenant Code of Conduct

### PR DESCRIPTION
**Pull request by tnir**
1. Fully adapted from [Contributor Covenant](https://www.contributor-covenant.org/) 2.1: https://www.contributor-covenant.org/version/2/1/code_of_conduct/
2. Uses newly-prepared https://groups.google.com/g/geminabox-maintainers/about (<geminabox-maintainers@googlegroups.com>) for this purpose

This would make contributors easier to participate in this project.

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

**Comment by tnir** [comment]
@geminabox/maintainers Feedback is welcome!

**Comment by deivid-rodriguez** [comment]
I think the idea of an email address is that people can report problems privately. Is this possible with Google Groups?

**Comment by tnir** [comment]
> Is this possible with Google Groups

@deivid-rodriguez Yes, you can configure only group members can read the message on Google Groups and I configured so at https://groups.google.com/g/geminabox-maintainers/about.

A non-maintainer (= an outside community member) can confirm it at https://groups.google.com/g/geminabox-maintainers/about as follows:

> Group members | can view conversations

while an outside community member cannot confirm who are registered as group members though.

**Comment by deivid-rodriguez** [comment]
Ah, right, that's ok then 👍.

**Pull request merged**
