### PR TITLE
update certificates

### PR DESCRIPTION
**Pull request by ahorek**
* the certificate from test fixtures is too short and considered insecure on new rubies, so just generate a more secure one
fixes https://github.com/geminabox/geminabox/issues/359
* use localhost instead of 127.0.0.1, because tests shouldn't depend on IPv4 protocol

### CODE REVIEW

**Comment by tnir** [comment]
Thanks. I tried to use a new certificate with valid `notBefore/notAfter` signed with the original 1024-bit key, so could not fix it on my local 😁

**Comment by tnir** [comment]
@tomlea Thoughts?

**Comment by tnir** [comment]
@rikas Could you merge this PR in advance to merged #366? Or choose someone else in charge of this?

**Comment by rikas** [comment]
@tnir I'm not very good with certificates and encryption stuff. I would prefer to not do it myself without the review of @sonots or @reggieb.

Tom Lea, the original maintainer is not around anymore. I hope one of the above will be... otherwise I'll do it myself.

**Review by reggieb — APPROVED** [review]
Looks good to me.

**Comment by rikas** [comment]
Ok, I'll merge then! This is from almost a year ago. PRs are taking a very long time to be merged due to inactivity 😞

**Comment by tnir** [comment]
Thanks @rikas and @reggieb!

**Comment by rikas** [comment]
Thanks for pushing this forward @tnir 👍

**Pull request merged**
