### PR TITLE
use streaming instead of direct gem serve

### PR DESCRIPTION
**Pull request by ValentineK**
I haven`t rised an issue, but I will explain here the reason of pull request.

I am moving my gemserver with geminabox from a vm to [Google Cloud Run](https://cloud.google.com/run) and using [Cloud Storage](https://cloud.google.com/storage) as gems storage to reduce running costs.  

In general it worked fine, but I faced an issue with [Google Cloud Run Quotas](https://cloud.google.com/run/quotas), Response could be not larger than 32 Mb. Its pretty rare that gem is larger than this limit, but still it exists, for example [wkhtmltopdf-binary-edge 0.12.4.0 (45.1 MB)](https://rubygems.org/gems/wkhtmltopdf-binary-edge) or [libv8-3.16.14.7-x86_64-darwin-14.gem (39 MB)](https://rubygems.org/gems/libv8/versions?page=4)
Cloud Run returns 500 and puts in log: `Response size was too large. Please consider reducing response size.`

Streaming solves the issue

### CODE REVIEW

**Comment by ValentineK** [comment]
I will rework on it

**Review by pboling — APPROVED** [review]
Awesome!

**Comment by pboling** [comment]
@tnir This is an awesome update.  Commenting to keep it from going stale.

**Comment by pboling** [comment]
This library needs to decide if it is dead or alive!

**Comment by pboling** [comment]
The staleness bot needs to be disabled if this repo isn't going to be actively managed.

**Comment by pboling** [comment]
Wahoo!

**Comment by pboling** [comment]
✳️ Oops. Damn.

**Pull request closed without merging**
