### PR TITLE
Patching the rubygems vs httpclient TLS version issue.

### PR DESCRIPTION
**Pull request by grahampiksel**
This allows the proxy to work again.

### CODE REVIEW

**Comment by sonots** [comment]
What was the problem?
Can you show error messages you got without this patch?
Could you explain why this patch fixes the issue correctly?

**Comment by grahampiksel** [comment]
The problem: 
Adding ``Geminabox.rubygems_proxy = true`` to config.ru had no observable effect. It was expected that it would proxy upstream to Rubygems.org if a gem was not held locally.

The error message under the hood:
```SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure```

The solution:
Change the SSL parameters on the httpclient to attempt a TLSv1 handshake rather than an SSLv3 handshake to Rubygem.org

**Comment by sonots** [comment]
I use proxy mode, but I do not get the error.
What is the version of httpclient in Gemfile.lock?
it seems https://github.com/nahi/httpclient/pull/204 fixed the issue.

**Comment by martinseener** [comment]
I would rather better update the httpclient instead of hard-code TLS1.0 because TLS1.0 is not secure anymore and it's better to automatically negotiate TLS (maybe TLS1.2) with rubygems. I would not merge this one here but instead update the gems!!!!

**Comment by sonots** [comment]
Agree, let me close

**Pull request closed without merging**
