### PR TITLE
remove has_rdoc from fixtures

### PR DESCRIPTION
**Pull request by ahorek**
there's a deprecation warning with recent versions of RubyGems that leads to test failures
https://www.rubydoc.info/github/rubygems/rubygems/Gem%2FSpecification:has_rdoc

### CODE REVIEW

**Review by tnir — APPROVED** [review]
That method was deprecated in RubyGems 1.8.5 (2011-05-31).

https://github.com/rubygems/rubygems/blob/v1.8.5/History.txt#L1-L6

**Comment by tnir** [comment]
@ahorek Thank you!

> [...] a deprecation warning [...] that leads to test failures

How did you run into such a failure on `rake test`? Ruby/RubyGems version?

**Comment by ahorek** [comment]
I guess the warning was messing with the expected output of some test, I don't really remember after a year :)

**Comment by ahorek** [comment]
https://github.com/geminabox/geminabox/pull/320 was about the same thing, maybe that rubygems version was too verbose...  that method was deprecated a long time ago, even if still works, it has practically no effect and it should be removed.

**Comment by tnir** [comment]
Got it. I agree with you.

**Pull request merged**
