### PR TITLE
Support for healthchecks

### PR DESCRIPTION
**Pull request by pcarrier**
This would be really neat to allow for easier monitoring.

The paths "happen" to match our conventions at Airbnb.

### CODE REVIEW

**Comment by pcarrier** [comment]
Is that a no?

**Comment by rabbitt** [comment]
@pcarrier :+1:

**Comment by cwninja** [comment]
As it's a rack app, and the config.ru that's intended for use is not part of the repo, this kind of customisation is best placed in there.

This way we get composition, rather than apps designed to be all things to all people.

For example:


``` ruby
require "rubygems"
require "geminabox"

Geminabox.data = "/var/geminabox-data" # ... or wherever

app = Rack::Builder.new do
  map "/ping" do
    run lambda{ |env| 
        [200, {}, ["OK"]]
    }
  end

  map "/health" do
    run lambda{ |env|
        Geminabox::Server.new.send(:load_gems)
        [200, {}, ["OK"]]
    }
  end

  map "/" do
     run Geminabox::Server
  end
end

run app
```

I've not tested the above code, but the overall concept makes sense.

**Comment by cwninja** [comment]
@pcarrier oh, sorry the ordering of my responses came out wrong. That's the danger of working in multiple tabs.

**Pull request closed without merging**
